baseUrl: $PRIMARY_SITE_URL
handle: default
hasUrls: true
language: en-US
name: 'https://clicklab.ddev.site/'
primary: true
siteGroup: bf731591-10b5-481e-a00f-bf5afd4b355d # https://clicklab.ddev.site/
sortOrder: 1
